<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Carros</title>
</head>
<body>
    <h1>Lista de Carros</h1>

    <ul>
        <li>${carro1.getMarca()} : ${carro1.getModelo()}</li>
        <li>${carro2.getMarca()} : ${carro2.getModelo()}</li>
    </ul>
</body>
</html>
